export const strings = {
  appName: 'OVO',
  login: 'Giriş yap',
  logout: 'Çıkış',
  emailOrUser: 'E-posta veya kullanıcı adı',
  password: 'Şifre',
  community: 'Topluluk',
  outfits: 'Kombinlerim',
  tryOn: 'Try-On',
  wardrobe: 'Dolabım',
  profile: 'Profil',
  wishlist: 'Favoriler',
  loading: 'Yükleniyor…',
  retry: 'Tekrar dene',
  errorGeneric: 'Bir hata oluştu.',
  errorNetwork: 'Bağlantınızı kontrol edin.',
  errorUnauthorized: 'Oturum süresi doldu. Tekrar giriş yapın.',
  errorRateLimit: 'İstek limiti aşıldı. Bir süre sonra tekrar deneyin.',
  errorServer: 'Sunucu hatası.',
  loginRequired: 'Bu alan için giriş yapmanız gerekir.',
  vote: 'Oy ver',
  pollsEmpty: 'Henüz oylama yok.',
  wardrobeEmpty: 'Dolabında kıyafet yok.',
  outfitEmpty: 'Kombin bulunamadı.',
  weatherLoadError: 'Hava durumu alınamadı.',
  tryOnStudioTitle: 'Stüdyo fotoğrafı',
  tryOnStudioMissing: 'Henüz stüdyo fotoğrafı yok. En az 3 referans foto ekleyip aşağıdan oluşturun.',
  tryOnPhotosTitle: 'Referans fotoğraflar',
  tryOnAddPhotoUrl: 'URL ile foto ekle',
  tryOnRegenerateStudio: 'Stüdyoyu fotolardan üret',
  tryOnRegenerateNeedPhotos: 'Stüdyo üretmek için en az 3 referans foto gerekir.',
  tryOnGarmentsTitle: 'Kıyafet seç (en az 3)',
  tryOnNeedThreeGarments: 'Render için en az 3 kıyafet seçin.',
  tryOnRender: 'Render al',
  tryOnRenderHint: 'Aynı kombin önbellekte varsa tekrar ücretlendirilmez.',
  tryOnResultTitle: 'Sonuç',
  tryOnPhotoUrlPlaceholder: 'https://… (yüklü görsel URL’i)',
  tryOnPhotoUrlRequired: 'Geçerli bir görsel URL’i girin.',
} as const;
