import { StyleSheet } from 'react-native';
import { colors } from '@/constants/colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  scrollContent: { padding: 16, paddingBottom: 40, gap: 20 },
  sectionTitle: { color: colors.text, fontSize: 17, fontWeight: '700', marginBottom: 8 },
  muted: { color: colors.textMuted, fontSize: 14, lineHeight: 20 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  studioImage: { width: '100%', aspectRatio: 3 / 4, borderRadius: 12, backgroundColor: colors.surface },
  renderImage: { width: '100%', aspectRatio: 9 / 16, borderRadius: 12, backgroundColor: colors.surface },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  garmentChip: {
    width: 88,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  garmentChipSelected: { borderColor: colors.accent },
  garmentThumb: { width: '100%', height: 88 },
  btn: {
    backgroundColor: colors.accent,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 8,
  },
  btnText: { color: colors.background, fontSize: 15, fontWeight: '600' },
  btnSecondary: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  btnSecondaryText: { color: colors.text, fontSize: 15, fontWeight: '600' },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.text,
    fontSize: 14,
    marginTop: 8,
    backgroundColor: colors.surface,
  },
  errorText: { color: colors.danger, fontSize: 13, marginTop: 8 },
  photoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
});
